[build]
  command = "npm run clean:install && npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18.17.0"
  NPM_VERSION = "10.2.4"
  NEXT_PUBLIC_BACKEND_URL = "${NEXT_PUBLIC_BACKEND_URL}"
  NEXT_PUBLIC_WEBSOCKET_URL = "${NEXT_PUBLIC_WEBSOCKET_URL}"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false

[functions]
  node_bundler = "esbuild"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
